---
title: "data_viz_class1"
output: github_document
date: "2026-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


loading packages
```{r message = FALSE}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

let's make a scatterplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

good to start it as a dataframe
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

# good to do this to easily save the scatterplot and view it later (make it equal to a new variable)
gg_temp_scatterplot = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + #makign scatterplot fancier (add colors and line)
  geom_point(alpha = .25) +
  geom_smooth(se = FALSE)

gg_temp_scatterplot
```
show faceting

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  facet_grid(. ~ name) # what vraibles do youwant separating rows (none so .), ~ what variable do you want separating columns (name)


weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  facet_grid(cols = vars(name)) # this is another way to do it, just specify the column that you want 
```

```{r}
weather_df |> 
  ggplot(aes(x=date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.5) + # change dot sizes based on precipitation
  geom_smooth(se = FALSE) + # se = false takes away error bars from the lines
  facet_grid(. ~ name)
```
make a plot of central park  tmax vs tmin only, and convert temperatures to farenheit 
```{r}

weather_df |>
  filter(name == "CentralPark_NY") |> 
  mutate(
    tmax = tmax * (9/5) + 32,    # don't have to make a new dataframe/dataset to convert temps, can just mutate in this dataframe for this plot 
    tmin = tmin * (9/5) + 32,   # without changing the whole dataset
  ) |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

hex plot
```{r message = FALSE}

weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```
# univariate plots
```{r}
weather_df |> 
  ggplot(aes(x = tmax)) +
  geom_histogram()
```


```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(. ~ name)
```

density plots
```{r}
weather_df |> 
  ggplot(aes(x = tmax, color = name)) +
  geom_density()

weather_df |> 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3) # the alpha = .3 makes the fill transparent
```



